version: '3.3'

#declarando rede a ser utilizada:
networks:
  aw-network:
    driver: bridge

#declarando volumes: para quando iniciarmos e paramrmos nossa aplicação, os dados do prometheus não sejam perdidos
volumes:
    prometheus_data:
    grafa_data:

#declarando serviços [próprio ctnr]:
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aw-network
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - aw-network
